name: Run Tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ 8.1, 8.2, 8.3, 8.4 ]
        symfony: [ '6.4.*', '7.2.*' ]
        exclude:
          - php: 8.1
            symfony: '7.2.*'

    name: PHP ${{ matrix.php }} / Symfony ${{ matrix.symfony }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, pdo_mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: Set Symfony Version
        run: echo "export SYMFONY_REQUIRE=${{ matrix.symfony }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Ensure Symfony Version
        run: composer require symfony/symfony:${{ matrix.symfony }} --with-all-dependencies

      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit